name: Integration Test

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Integration Test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer update --prefer-stable --no-interaction --no-progress --ansi

      - name: Run Test Cases
        run: composer run test:integration
        env:
          INTEGRATION_TEST_ENABLED: true
          ACS_ACCESS_KEY_ID: ${{ secrets.ACS_ACCESS_KEY_ID }}
          ACS_ACCESS_KEY_SECRET: ${{ secrets.ACS_ACCESS_KEY_SECRET }}
          MNS_ENDPOINT: ${{ secrets.MNS_ENDPOINT }}
